### ISSUE TITLE
time saving

### ISSUE THREAD

**Issue by wzylin** [nanoporetech/ont-assembly-polish#1]
HI,
If I already used Canu to do the assembly.
How can I use this pipeline to do the rest of the jobs? 
For saving time, I dont wanna assemble it again.
Thanks.

**Comment by bsipos** [comment]
Hi wzylin,

To start with an existing assembly do the following:

1) Edit config.mk as usual
1) issue "make wdir" to create working directory
3) Place the assembly under <working_directory>/canu-assembly/canu.contigs.fasta
4) Comment out most lines for the canu assembly target in analysis.mk
canu_assembly: $(CANU_CONTIGS) $(WDT)
$(CANU_CONTIGS): $(NANOPORE_READS)
    @echo Assembling nanopore reads using canu.
    @canu\
     \#    -p $(CANU_PREFIX) \
      \#   -d $(CANU_DIR) \
      \#   genomeSize=$(CANU_GENOME_SIZE) \
      \#   -nanopore-raw $(NANOPORE_READS) $(CANU_PARAMETERS)
5) issue "make all" to perform correction with racon and pilon

Hope this helps, please write a message if you run into any problems.

Botond
