### ISSUE TITLE
canu error: Can't locate canu/Defaults.pm

### ISSUE THREAD

**Issue by mortunco** [nanoporetech/ont-assembly-polish#10]
Hi

I was able to set up the docker image but when I run canu in the docker environment, i get this error.

```
root@42f0d6544e02:/home/ont-assembly-polish# canu
Can't locate canu/Defaults.pm in @INC (you may need to install the canu::Defaults module) (@INC contains: /usr/local/bin/../lib/site_perl /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /usr/local/bin/canu line 52.
BEGIN failed--compilation aborted at /usr/local/bin/canu line 52.
```

I found this issue in canu's repo. https://github.com/marbl/canu/issues/47 which is very similar to the error I get. They say it is related to perl version in the machine. So I think you may want to consider perl version in the docker.
(If you think this is not related to problem, just forget what I said )

Thank you very much for your help,

Best regards,

Tunc.

**Comment by bsipos** [comment]
Hello! 
Thanks for reporting this issue, it was caused by a bug in the Dockerfile. It should build now with the latest commit.
