### ISSUE TITLE
Difficulty building from Docker

### ISSUE THREAD

**Issue by jussher** [nanoporetech/ont-assembly-polish#11]
I encountered the following error when trying to build from Docker:
The command '/bin/sh -c git clone https://github.com/marbl/canu.git &&    cd canu/src && make -j && cd -' returned a non-zero code: 2
make: *** [build] Error 2

In the log file, this error is repeatedly returned: g++: internal compiler error: Killed (program cc1plus)
eg
Makefile:651: recipe for target '/opt/canu/Linux-amd64/obj/lib/libcanu.a/overlapInCore/overlapReadCache.o' failed
g++: internal compiler error: Killed (program cc1plus)

Any advice would be much appreciated.

**Comment by bsipos** [comment]
Hello,

The docker build works for me on the latest commit. Do you have any restrictions on the amount of memory the build process can use? My guess is that running out of memory is the reason the compiler is killed.

Cheers

**Comment by jussher** [comment]
Hi,

Thanks for your prompt response. I was trying to build on a laptop, and you are right, the CPU usage peaked just before it crashed, so that is probably the explanation. Therefore I tried building it on the server, however I got the following error:

docker$ make build
docker build --no-cache --pull --build-arg CACHEBUST= -t ont-assembly-polish .
flag provided but not defined: --build-arg
See 'docker build --help'.
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 2

A Google search suggested it might be a version error of Docker, however the server is apparently running the latest version.

Do you have any suggestions?

Cheers

**Comment by bsipos** [comment]
Hi,

I am puzzled why this problem occurs for you, but it can be fixed by changing the build line in the Makefile to the following:

`docker build --no-cache --pull -t $(IMAGE) .`

Cheers

**Comment by jussher** [comment]
Hi,

That worked thanks. I also had to delete the line 39 from the Dockerfile:
ARG CACHEBUST

Thanks for your help

**Comment by jussher** [comment]
Hi,

That worked thanks.

However I now have encountered an issue however with running the pipeline. If I make all without altering the config.mk file it seems to run okay until it returns an error that there are no fastq files. If I then modify the config.mk file to say what the fastq file (in this case Isolate_35.fastq is I get the following error:

make: *** No rule to make target 'Isolate_35.fastq', needed by 'assembly-polish/racon.contigs.fasta'.  Stop

Thanks,

James

On 10/01/2018, at 5:08 AM, Botond Sipos <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I am puzzled why this problem occurs for you, but it can be fixed by changing the build line in the Makefile to the following:

docker build --no-cache --pull -t $(IMAGE) .

Cheers

**Comment by bsipos** [comment]
Could you please specify the input fastqs by the absolute path and try again?

Cheers

**Comment by jussher** [comment]
Hi,

I launch the session with:
docker run -v ~/SCRATCH/JAMES_DATA/MinION/Myanmar_plasmid:/data -it ont-assembly-polish

In the config.mk file I put:
# Parent directory to pipeline workspace:
WORKSPACE=.
# Pipeline name:
PIPELINE_NAME=assembly-polish
# Pipeline working directory:
WDIR=$(WORKSPACE)/$(PIPELINE_NAME)
# Results directory:
RES=$(WDIR)/results
# Pipeline git repo:
REPO=https://github.com/nanoporetech/ont-assembly-polish.git<http://github.com/nanoporetech/ont-assembly-polish.git>

# Custom pipeline parameters:

# Input files:




NANOPORE_READS=~/SCRATCH/JAMES_DATA/MinION/Myanmar_plasmid/Isolate_23_combined.fastq
ILLUMINA_READS_PAIR1=~/SCRATCH/JAMES_DATA/MinION/Myanmar_plasmid/Illumina/processed_Strain-B23_S97_L001_R1_001.fastq.gz
ILLUMINA_READS_PAIR2=~/SCRATCH/JAMES_DATA/MinION/Myanmar_plasmid/Illumina/processed_Strain-B23_S97_L001_R2_001.fastq.gz

# Canu configuration:
CANU_GENOME_SIZE=100k
# Extra options passed to canu, refer to http://canu.readthedocs.io for more information:
CANU_PARAMETERS=

# Racon configuration:
# Use racon for polishing or not:
USE_RACON=yes
# Extra options passed to racon:
RACON_PARAMETERS=

# BWA configuration:
# Extra options passed to BWA mem:
BWA_PARAMETERS=

# Pilon configuration:

When I “make all” I still get the following:
make: *** No rule to make target '/root/SCRATCH/JAMES_DATA/MinION/Myanmar_plasmid/Isolate_23_combined.fastq', needed by 'assembly-polish/racon.contigs.fasta'.  Stop.

Thanks,

James


On 11/01/2018, at 9:02 PM, Botond Sipos <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you please specify the input fastqs by the absolute path and try again?

Cheers

**Comment by bsipos** [comment]
I see. The correct path for the fastq files would be /data/Isolate_23_combined.fastq and so forth as you have mounted in the container ~/SCRATCH/JAMES_DATA/MinION/Myanmar_plasmid under /data.

Let me know if it is working that way.

Cheers.

**Comment by jussher** [comment]
Hi,

I tried:
docker run -v ~/SCRATCH/JAMES_DATA/MinION/Myanmar_plasmid:/data -it ont-assembly-polish

With the following in the config.mk file:
NANOPORE_READS=/data/Isolate_23_combined.fastq
ILLUMINA_READS_PAIR1=/data/Illumina/processed_Strain-B23_S97_L001_R1_001.fastq.gz
ILLUMINA_READS_PAIR2=/data/Illumina/processed_Strain-B23_S97_L001_R1_001.fastq.gz

But still got:
make: *** No rule to make target '/data/Isolate_23_combined.fastq', needed by 'assembly-polish/racon.contigs.fasta'.  Stop.

I also tried: /home/ont-assembly-polish/data/Isolate_23_combined.fastq

But got the same result.

When I look in the /data/ folder I don’t see my data. Also the /data/simulated folder it is empty. Is it somehow failing to recognise it when I run the docker command?

Cheers,

James
On 12/01/2018, at 2:08 AM, Botond Sipos <notifications@github.com<mailto:notifications@github.com>> wrote:


I see. The correct path for the fastq files would be /data/Isolate_23_combined.fastq and so forth as you have mounted in the container ~/SCRATCH/JAMES_DATA/MinION/Myanmar_plasmid under /data.

Let me know if it is working that way.

Cheers.

**Comment by bsipos** [comment]
It seems that your data directory is not mounted. Could you try with "-v /root/SCRATCH/JAMES_DATA/MinION/Myanmar_plasmid:/data" . Until your data shows up under /data in the container there is no chance that the pipeline will work.

**Comment by jussher** [comment]
Thanks, that makes sense. I'm just on leave now but will try that on my return.

Cheers,

James

On 12 Jan 2018 21:46, Botond Sipos <notifications@github.com> wrote:

It seems that your data directory is not mounted. Could you try with "-v /root/SCRATCH/JAMES_DATA/MinION/Myanmar_plasmid:/data" . Until your data shows up under /data in the container there is no chance that the pipeline will work.

**Comment by jussher** [comment]
I’m afraid it is still not mounting the data directory. I have tried searching Docker discussion forums for a solution but am yet to find one. Any other suggestions?

On 12/01/2018, at 9:45 PM, Botond Sipos <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems that your data directory is not mounted. Could you try with "-v /root/SCRATCH/JAMES_DATA/MinION/Myanmar_plasmid:/data" . Until your data shows up under /data in the container there is no chance that the pipeline will work.

**Comment by bsipos** [comment]
It is unfortunate that docker would not mount your data directory. You could use the pipeline outside docker.
