### ISSUE TITLE
interested by the commands used to evaluate accuracy

### ISSUE THREAD

**Issue by splaisan** [nanoporetech/ont-assembly-polish#12]
HI,
I liked a lot your evaluation but do not find which lastal and mummer commands you used to get to the shown histograms.
If you have time, could you please share a bit more on the analysis you did, I would like to repeat it with my own yeast data from Sequel and minION to compare the outcomes.
Thanks

**Comment by bsipos** [comment]
Hi,

The accuracies were calculated using the [compare_genomes_lastal.py](https://github.com/nanoporetech/wub/blob/master/scripts/compare_genomes_lastal.py) and [compare_genomes_dnadiff.py](https://github.com/nanoporetech/wub/blob/master/scripts/compare_genomes_dnadiff.py) scripts from the [wub](http://wub.readthedocs.io/en/latest/) package. They call lastal (with parameters -a 1 -b 1) and dnadiff (with default parameters) respectively. The scripts then parse the results and in the case of lastal filter for the best scoring alignments.
Let me know if you have any more questions.

Cheers,
Botond
