### ISSUE TITLE
Need to externalize config.mk outside the container

### ISSUE THREAD

**Issue by rusalkaguy** [nanoporetech/ont-assembly-polish#15]
Good docker container practices say that I shouldn't have to modify the container to use it to run my analysis. There should be a run/exec command where I specify an external location for my config.mk, and all temp files and results are also outside the container. 

Context: I work in an academic translational research lab. We use the university's HPC cluster. They do not support docker (for security reasons), but they do support Singularity, which enforces read-only contianers. So, I had no trouble using your Dockerfile to build a docker container and then build a singularity container from that, and I can start it up on my cluster. But now I'm a little stuck, as I can't modify config.mk.

Perhaps there's a flag I haven't found to run it with an externalized config.mk? (it would be nice to have a simple example worked out in the README.md, perhaps with a small amount of  test data to validate everything is functioning, etc).

**Comment by bsipos** [comment]
Hello,

I assume you are still mounting a data directory to your container. If that is writable a simple workaround would be to check out the repository under that. This would allow you to edit the config file.
Let me know if this works for you.

Regards,
Botond

**Comment by rusalkaguy** [comment]
Yes, I'm mounting /data to shared drive, so I can try that. Thanks for the quick reply!
