### ISSUE TITLE
Run without docker

### ISSUE THREAD

**Issue by BertBog** [nanoporetech/ont-assembly-polish#16]
Dear,

Is it possible to run the pipeline without using docker?
I can install dependencies etc manually, but prefer not to use docker.

Best regards,
Bert

**Comment by bsipos** [comment]
Hello,

It is possible to run the pipeline without docker, just make sure you have installed all the dependencies (https://github.com/nanoporetech/ont-assembly-polish#application-dependencies).

Regards,
Botond
