### ISSUE TITLE
racon output

### ISSUE THREAD

**Issue by fanhuan** [nanoporetech/ont-assembly-polish#17]
Hi,

Am I missing something or why in analysis.mk(line 45) it goes like:

@$(WDIR)/racon -t $(CORES) $(NANOPORE_READS) $(MINIMAP_OVERLAPS) $(CANU_CONTIGS) $(RACON_CONTIGS)

instead of 

@$(WDIR)/racon -t $(CORES) $(NANOPORE_READS) $(MINIMAP_OVERLAPS) $(CANU_CONTIGS) > $(RACON_CONTIGS)

?
I had to add the greater-than sign in order for the pipeline to work. Otherwise racon prints the output to the screen.

Thanks ahead.

**Comment by bsipos** [comment]
Thanks for reporting this issue! The latest racon versions changed how they output the contigs so your fix was necessary.
