### ISSUE TITLE
*** No rule to make target 'modules'. Stop.

### ISSUE THREAD

**Issue by TseWue** [nanoporetech/ont-assembly-polish#18]
Hi everyone,

I am trying to get the ont-assembly-polish pipeline to run on our server (no docker allowed unfortunately) and when I issue the _$make all_ command I get the following error:

[tswuethrich@submit01 ont-assembly-polish]$ make all
(cd ./assembly-polish && git clone https://github.com/isovic/racon.git racon.build && cd racon.build && make modules && make tools && make -j) &&\
 mv ./assembly-polish/racon.build/bin/racon ./assembly-polish/ && rm -rf racon.build
Cloning into 'racon.build'...
remote: Enumerating objects: 1994, done.
remote: Total 1994 (delta 0), reused 0 (delta 0), pack-reused 1994
Receiving objects: 100% (1994/1994), 8.92 MiB | 3.17 MiB/s, done.
Resolving deltas: 100% (1271/1271), done.
make[1]: Entering directory /gpfs/homefs/ifik/tswuethrich/ONT/mock_hybrid_assembly/nanoporetech_pipeline/ont-assembly-polish/assembly-polish/racon.build
**make[1]: *** No rule to make target modules.  Stop.**
make[1]: Leaving directory `/gpfs/homefs/ifik/tswuethrich/ONT/mock_hybrid_assembly/nanoporetech_pipeline/ont-assembly-polish/assembly-polish/racon.build'
**make: *** [assembly-polish/racon] Error 2**

I did a little investigation and (correct me if I'm wrong - I'm just a beginner) I found that the problem somehow occurs in the command of the analysis.mk file on line 36:

[...]
build_racon: $(WDIR)/racon
$(WDIR)/racon: $(WDT)
	(cd $(WDIR) && git clone https://github.com/isovic/racon.git racon.build && cd racon.build **&& make modules** && make tools && make -j) &&\
	 mv $(WDIR)/racon.build/bin/racon $(WDIR)/ && rm -rf racon.build
[...]

The _racon.build_ directory is being built with the contents
_dir_ vendor
_dir_ test
_dir_ src
_dir_ scripts
README.md
LICENSE
CMakeLists.txt

Do I have to specify any other thing (like modifying another file within this directory?) I already asked our in-house linux geek and he suggested to turn to you for help. :-)

Thanks a bunch and have a nice day!
Best,
-Tse

**Comment by bsipos** [comment]
Hello,

The commands for compiling racon were outdated. I have fixed the problem and pushed to GitHub.
Please try running your analysis again.

Regards,
Botond

**Comment by TseWue** [comment]
Hi,

Thanks a lot, yes it worked now. However, not entirely, I encounter a segfault at

[...]
Mapping nanopore reads onto canu contings using minimap.
/bin/sh: line 1: 18914 Segmentation fault      minimap ./assembly-polish/canu-assembly/canu.contigs.fasta /gpfs/homefs/ifik/tswuethrich/ONT/mock_hybrid_assembly/ont_reads_mock/all_mock_stringent.fastq > ./assembly-polish/minimap_overlaps.paf
make: *** [assembly-polish/racon.contigs.fasta] Error 139
[...]

The _minimap_overlaps.paf_ is written but it remains empty. The problem persists everytime I rerun the pipeline. My files are not particularly big, do you have an idea what the problem could be?

Thanks for your help.
Best,
Tse

**Comment by bsipos** [comment]
Hello,

I have updated the pipeline to work with minimap2 (instead of minimap). Could you please pull and try again?

Regards,
Botond
