### ISSUE TITLE
[ERROR] failed to open file './assembly-polish/canu-assembly/canu.contigs.fasta' make: *** [assembly-polish/racon.contigs.fasta] Error 1

### ISSUE THREAD

**Issue by pneumowidow** [nanoporetech/ont-assembly-polish#19]
Hello,

I've been trying to run your pipeline from the config.mk file, but I keep getting the following error:
`[ERROR] failed to open file './assembly-polish/canu-assembly/canu.contigs.fasta'
make: *** [assembly-polish/racon.contigs.fasta] Error 1`

I checked the Canu-assembly subfolder and indeed, the contigs.fasta file is not present but I don't know why. I'm running Canu 1.8 and technically it runs.  

**This is what I have in the canu-assembly subfolder:**
![image](https://user-images.githubusercontent.com/43600124/51995335-cfc3b900-24b2-11e9-9ffe-578d15fe7a14.png)

**The detailed output from, the Canu run is here:**
![image](https://user-images.githubusercontent.com/43600124/51995565-38ab3100-24b3-11e9-93af-265e09f35247.png)
![image](https://user-images.githubusercontent.com/43600124/51995613-4fea1e80-24b3-11e9-9973-ee6faf45eb91.png)
![image](https://user-images.githubusercontent.com/43600124/51995664-67290c00-24b3-11e9-8c69-3bf14a885de1.png)

Do you think this is problem with the pipeline or with the Canu on my system? Honestly, I would gladly run it on Docker, but my computer just doesn't have the space. I really hope you can help me rectify this problem.

Thanks

**Comment by bsipos** [comment]
Hello,

I think this might be a canu problem. Could you please try assembling your reads just using canu (outside the pipeline). Then you could raise the issue with the canu developers if something looks wrong.

Best,
Botond

**Comment by pneumowidow** [comment]
Hi again.

Yeah, I just realized it had to do with one of the default settings for Canu which was basically chucking out all my reads. I've tuned it off now and it's running. 

Thank you.

**Comment by diegusleik** [comment]
Hello pneumowidow:

Can I ask you exactly which parameter did you turn off? I'm having the same problem as you

**Comment by pneumowidow** [comment]
Hi @diegusleik 

I don't remember now....but I think it had to do with the `contigFilter` parameter. Anyway, the code I ended up using in the config.mk file that worked was this:

***# Canu configuration: Use the size of your genome
`CANU_GENOME_SIZE=2.3m`
***# Extra options passed to canu, refer to http://canu.readthedocs.io for more information:
`CANU_PARAMETERS= -minReadLength="1000" stopOnReadQuality="false" -corMinCoverage="0" -contigFilter="5 500 1.0 0.5 2" useGrid="false" maxThreads="12" -correctedErrorRate="0.12"`

You probably need to fine tune the genome size to that of your organism but the other parameters should work for you because they are the current default parameters on CANU. Make sure to include the **""** when specifying a parameter argument. That could also give you a run error if you don't do it like that.

Let me know if it works for you.
