### ISSUE TITLE
samtools sort

### ISSUE THREAD

**Issue by tomsauv** [nanoporetech/ont-assembly-polish#2]
Hi I am not sure if its my system but I had an error at the 'samtools sort' step with the original command line found in "analysis.mk" file.
I modified as follows and the pipeline completed to the end without error (added 'o' and '.bam')

samtools sort -@ $(CORES) -o $(BWA_BAM_PREFIX).bam

Thanks,
Thomas

**Comment by bsipos** [comment]
Thanks for reporting this. It seems like a samtools version issue. With the version I am using (0.1.19-96b5f2294a) the -o option does not work with multi-threaded sort (-@).

**Comment by tomsauv** [comment]
OK thanks for clarifying. I am using the latest samtools (1.3.1), so many users (or new users) may encounter this issue...
Thanks again for putting this pipeline together
Thomas
