### ISSUE TITLE
[ERROR] /bin/sh: 1: cmake: not found

### ISSUE THREAD

**Issue by fabiodepa** [nanoporetech/ont-assembly-polish#20]
Hi,
I run this pipeline from the docker container, after building it as detailed in the README.md  provided. However, I get an error while processing because it states that cmake is not found in the path. The docker building gave me no errors so I can not understand why the pipeline did not found "cmake" while running in the container.
I attached the last part of the massages before the stop.

Thank you for any help
Fabio

[ONT_ASSEMBLY_POLISH.txt](https://github.com/nanoporetech/ont-assembly-polish/files/3054736/ONT_ASSEMBLY_POLISH.txt)

**Comment by bsipos** [comment]
Hi,
cmake is needed for building racon. I have added this dependency to the Dockerfile. Please try building again.

Best,
Botond
