### ISSUE TITLE
big genome ?

### ISSUE THREAD

**Issue by colindaven** [nanoporetech/ont-assembly-polish#23]
Hi,

I have a couple of rat assemblies already I'd like to polish - but not assemble. I assume canu is being used for an initial assembly. Can the canu stage be skipped if an assembly exists already ?

Thanks

**Comment by bsipos** [comment]
Hi!

I recommend not using this pipeline for your data. I think it would be the best if you did two-three rounds of racon polishing, then [medaka](https://github.com/nanoporetech/medaka), and finally polishing using pilon if you also have Illumina reads.

Best,
Botond

**Comment by colindaven** [comment]
Thanks, we'll write some SLURM scripts ourselves then,
