### ISSUE TITLE
request for test data and results

### ISSUE THREAD

**Issue by GodloveD** [nanoporetech/ont-assembly-polish#24]
I'm an admin trying to install this pipeline on behalf of a user.  It would be wonderful if you could include some dummy data in the repo along with an example including the expected output.   This would make it much easier for a lowly admin to ensure that it is installed correctly and might also provide a starting point for CI/CD testing.

Thanks for considering this request!  😄

**Comment by mjmillerlab** [comment]
Absolutely. I'm working on getting that up soon. Thanks for the interest. Give me a bit of time to upload this!

**Comment by bsipos** [comment]
This pipeline is fort all practical purposes retired! It is a much better idea to use katuali (https://github.com/nanoporetech/katuali ) which is doing a better job of polishing with nanopore reads and then manually run pilon on the results.

Best,
Botond

**Comment by GodloveD** [comment]
I will convey this message to the end user.  Thank you @bsipos.
