### ISSUE TITLE
Unable to find image 'ont-assembly-polish:latest' locally

### ISSUE THREAD

**Issue by okazakib** [nanoporetech/ont-assembly-polish#26]
Hello,

I am unable to run the container on docker. I get the following error:

`docker: Error response from daemon: pull access denied for ont-assembly-polish, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.`

Can you please help me resolve this.

Thank you.

**Comment by bsipos** [comment]
This seems to be a docker issue, please refer to the docker manual or relevant forums to resolve it.
