### ISSUE TITLE
Using pipeline for polishing of ONT transcriptomic data (from cDNA sequencing) with short Illumina reads

### ISSUE THREAD

**Issue by MartinTes** [nanoporetech/ont-assembly-polish#27]
Hello,

I would like to ask you whether this pipeline could be applied also for the polishing of transcriptomic data from cDNA Oxford Nanopore sequencing by using short Illumina reads? If not, are there also any other state-of-the-art alternatives for working with cDNA data? We first generated transcriptomes from six parrot species where only one species had a sequenced genome available. However, due difficulties to process such reference-free data and also due to obtained relatively low coverage we resequenced the same samples also by Nextseq Illumina sequencing. I would be very grateful for any suggestions.

**Comment by bsipos** [comment]
Hello! This pipeline was not built to handle cDNA data as the assembler it uses (canu) is not able to handle that data. Unfortunately, I am not aware of any equivalent pipeline which would work on cDNA.

**Comment by MartinTes** [comment]
Hi @bsipos , thank you for your response.

**Comment by MartinTes** [comment]
Hi @bsipos, thank you for your response.
