### ISSUE TITLE
samtools problem

### ISSUE THREAD

**Issue by gaworj** [nanoporetech/ont-assembly-polish#3]
Hello,

we have successfully installed ont-assembly polish pipeline but I find two problems. First is related to samtools command section in "analysis.mk" file:

@echo Aligning Illumina reads using BWA mem.
	@bwa mem -t $(CORES) $(BWA_PARAMETERS) $(RACON_CONTIGS)  $(ILLUMINA_READS_PAIR1) $(ILLUMINA_READS_PAIR2)\
| samtools view -S -b -u - | samtools sort -@ $(CORES) - $(BWA_BAM_PREFIX)

In such case pipeline crashes.. We find that correcting commands this way helps:

@echo Aligning Illumina reads using BWA mem.
	@bwa mem -t $(CORES) $(BWA_PARAMETERS) $(RACON_CONTIGS)  $(ILLUMINA_READS_PAIR1) $(ILLUMINA_READS_PAIR2) | samtools view -S -b -u - | samtools sort - $(BWA_BAM_PREFIX)

Second issue is related to racon installation/working - I find it several days ago:
After pipeline start racon shows this message:

/usr/bin/ld: ./bin/racon: undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'
/usr/bin/ld: note: 'clock_gettime@@GLIBC_2.2.5' is defined in DSO /lib64/librt.so.1 so try adding it to the linker command line
/lib64/librt.so.1: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[1]: *** [linux] Error 1
make[1]: Leaving directory `/home/data/analysis/janek/E_albertii_5-2/E_albertii_5-2_polish_v1/racon.build'
make: *** [/home/data/analysis/janek/E_albertii_5-2/E_albertii_5-2_polish_v1/racon] Error 2

I found on racon website that new version is available. Maybe that's the case..

Thanks,
Jan

**Comment by bsipos** [comment]
Hello,

Thanks for reporting these issue. I will fix the samtools sort issue ASAP. 
Regarding the racon issue: please report it to https://github.com/isovic

Regards,
Botond Sipos
