### ISSUE TITLE
docker image fails with git clone of ont-assembly-polish

### ISSUE THREAD

**Issue by biobenkj** [nanoporetech/ont-assembly-polish#5]
Hi,

Thank you for building this workflow and the associated docker image! When I download and build the docker image for ont-assembly-polish, it fails on the git clone step:

```
# Clone the ont-assembly-polish project:
ARG CACHEBUST
RUN DUMMY=${CACHEBUST} GIT_SSL_NO_VERIFY=wizardry git clone https://git.oxfordnanolabs.local/bsipos/ont-assembly-polish.git
```

The error states that git.oxfordnanolabs.local doesn't exist (exit status 128).
However, if you adjust to the master branch for ont-assembly-polish, it succeeds.

```
ARG CACHEBUST
RUN DUMMY=${CACHEBUST} GIT_SSL_NO_VERIFY=wizardry git clone https://github.com/nanoporetech/ont-assembly-polish.git
```

Should I set up a pull request?

**Comment by bsipos** [comment]
Thanks for reporting this issue. I pushed out a fix, please try the build again on the HEAD.
