### ISSUE TITLE
Applying this on Pacbio sequencing methodology ?

### ISSUE THREAD

**Issue by mortunco** [nanoporetech/ont-assembly-polish#9]
Hi,

Can I apply this method on reads from pacbio sequencing. I have already finished canu assembly on my reads.

what I have:
Paired illumina reads
Pacbio Reads

Sorry for my ignorant question,

Best,
T.

**Comment by bsipos** [comment]
Hello,

If you already have the canu assembly then I suggest you use [pilon](https://github.com/broadinstitute/pilon/wiki) with the Illumina reads on the contigs according to the [instructions](https://github.com/broadinstitute/pilon/wiki/Requirements-&-Usage).

Cheers
